### ISSUE TITLE
Change EntropyRng arguments to impl Rng + CryptoRng

### ISSUE THREAD

**Issue by JayPavlina** [lovesh/signature-schemes#12]
`EntropyRng` is deprecated in `rand 0.7`. Arguments using it should be changed to `impl Rng + CryptoRng`.

**Comment by lovesh** [comment]
Fixed here https://github.com/lovesh/signature-schemes/commit/a3dc88356c031fb98f8374655ffb1a235518c2ba

**Comment by JayPavlina** [comment]
Is there a reason you did `RngCore` instead of `Rng`?

**Comment by lovesh** [comment]
Probably because i was using `RngCore` elsewhere as well. I see now that the Rust docs advise to use `Rng`. Will change.

**Comment by lovesh** [comment]
[Changed to Rng](https://github.com/lovesh/signature-schemes/commit/a9e160c69bc2ba42383d71df118106b56cb398a9). I don't know if it makes a difference but blindly following the Rust docs here.
