### ISSUE TITLE
The bls crate name has a typo

### ISSUE THREAD

**Issue by JayPavlina** [lovesh/signature-schemes#14]
The bls crate is named `bls_acml` instead of `bls_amcl`. See the [Cargo.toml](https://github.com/lovesh/signature-schemes/blob/master/bls/Cargo.toml).

**Comment by lovesh** [comment]
Thanks. [Fixed](https://github.com/lovesh/signature-schemes/commit/a9e160c69bc2ba42383d71df118106b56cb398a9).
