### ISSUE TITLE
Release on crates.io ?

### ISSUE THREAD

**Issue by andrewjstone** [lovesh/signature-schemes#4]
Hi @lovesh,

This crate is super useful. Are you opposed to creating release tags and pushing to crates.io? It may make it easier for others to find and use.

Thanks!

**Comment by lovesh** [comment]
Hi. I am glad its helpful. I was doing some refactoring and fixing the MuSig as one of the issues points out. I will try to get this crate published over the weekend.

**Comment by andrewjstone** [comment]
Great. Thanks!

**Comment by lovesh** [comment]
Released here https://crates.io/crates/bls_acml

**Comment by andrewjstone** [comment]
> Released here https://crates.io/crates/bls_acml

Thanks!
